server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              "[/**]":
                allowedOrigins: [ "${CORS_ALLOWED_ORIGINS:http://localhost:3000}" ]
                allowedMethods: [ "GET","POST","PUT","DELETE","OPTIONS" ]
                allowedHeaders: [ "Authorization","Content-Type" ]
                allowCredentials: true
          routes:
            - id: auth
              uri: http://auth:8081          # <-- docker service name
              predicates: [ Path=/auth/** ]
              filters: [ StripPrefix=1 ]
            - id: tasks
              uri: http://tasks:8082
              predicates: [ Path=/tasks/** ]
              filters: [ StripPrefix=1 ]

  security:
    oauth2:
      resourceserver:
        jwt:
          # Gateway valida HS256 con la misma clave que firma Auth
          secret-key: ${JWT_SECRET:dev-change-me-please-32bytes}
