services:
  gateway:
    build: ./gateway
    container_name: gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=fb72f4caee805fd3d45e807c22dc9a27e28ad605b824e7c7837a07f7961ba308   # Same as Auth
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    ports:
      - "8080:8080"         # We expose only the API Gateway
    depends_on:
      - auth
      - tasks
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  auth:
    build: ./auth-service
    container_name: auth
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=fb72f4caee805fd3d45e807c22dc9a27e28ad605b824e7c7837a07f7961ba308
      - JWT_ISSUER=auth-local
      - JWT_ACCESS_MINUTES=10080 # 7 days
    volumes:
      - auth_data:/data      # H2 database persistence
    # No expose the port to the host (only accessible through the internal network)
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8081/actuator/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  tasks:
    build: ./task-service
    container_name: tasks
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - tasks_data:/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8082/actuator/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  auth_data:
  tasks_data:
