server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:file:/data/tasksdb;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: update